INSERT INTO products (id, sku, slug, name, description, price, category_id, brand_id, status, created_at, updated_at) VALUES

    -- ===== Acessórios / Sparco =====
    (gen_random_uuid(), 'SPA-CONCHA-FIXO', 'banco-concha-esportivo-fixo-tecido-confortavel-racing-sparco', 'Banco Concha Esportivo Fixo Racing Sparco', 'Banco concha esportivo Sparco fixo em tecido confortável, indicado para uso esportivo diário.', 3499.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'sparco'), 'ACTIVE', NOW(), NOW()),

    -- ===== Acessórios / Metal Horse =====
    (gen_random_uuid(), 'MH-ENDURANCE-M', 'banco-concha-racing-endurance-m-metal-horse-homologado-fia', 'Banco Concha Racing Endurance M Metal Horse', 'Banco concha Metal Horse Endurance M homologado FIA, indicado para uso em competição.', 5999.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-SPORTSTER-RECL', 'banco-concha-reclinavel-metal-horse-sportster-c-trilho', 'Banco Concha Reclinável Metal Horse Sportster com Trilho', 'Banco concha Metal Horse Sportster reclinável, acompanha trilho deslizante para ajuste de posição.', 3299.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'MH-STREET-RS', 'banco-street-rs-tecido-preto-e-xadrez-vermelho-metal-horse', 'Banco Street RS Metal Horse Tecido Xadrez', 'Banco Street RS Metal Horse em tecido preto e xadrez vermelho, indicado para uso diário.', 2199.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),

    -- ===== Escapamento / Pro Line =====
    (gen_random_uuid(), 'PL-PONTEIRA-35', 'abafador-esportivo-inox-pro-line-ponteira-35-race-chrome', 'Abafador Esportivo Inox Pro Line Ponteira 3.5" Race Chrome', 'Abafador esportivo Pro Line em aço inox com ponteira 3.5 polegadas cromada, acabamento Race Chrome.', 529.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'pro-line'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'PL-JETTA-DUPLA', 'escape-traseiro-jetta-2012-200cv-211cv--ponteira-dupla-inox', 'Escape Traseiro Jetta 200cv/211cv Ponteira Dupla Inox Pro Line', 'Escape traseiro Pro Line para Jetta 200cv/211cv, ponteira dupla em aço inox.', 1899.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'pro-line'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'RON-RC493FL', 'abafador-escapamento-esportivo-inox-4polegadas-pro-line-rc493fl', 'Abafador Escapamento Esportivo Inox 4" Pro Line RC493FL', 'Abafador esportivo Pro Line RC493FL em aço inox, ponteira 4 polegadas, som mais grave e encorpado.', 449.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'pro-line'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'RON-DIFUSOR-UNIV', 'difusor-escape-eletrnico-universal-inox-pro-line-esportivo', 'Difusor de Escape Eletrônico Universal Inox Pro Line', 'Difusor de escape eletrônico Pro Line em aço inox, encaixe universal, acabamento esportivo.', 389.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'pro-line'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / Metal Horse =====
    (gen_random_uuid(), 'MH-ADAPT-6AN', 'adaptador-fmea-6an-an6-metal-horse', 'Adaptador Fêmea 6AN AN6 Metal Horse', 'Adaptador fêmea 6AN Metal Horse em alumínio usinado, uso em linhas de combustível e óleo.', 89.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-CONEXAO-8AN90', 'conexo-8an-an8-curva-90-graus-metal-horse-mhca', 'Conexão 8AN AN8 Curva 90° Metal Horse MHCA', 'Conexão Metal Horse MHCA 8AN curva 90°, alta vedação para sistemas de combustível e óleo.', 119.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-INTERC-STREET3', 'intercooler-street-3-polegadas-grande--metal-horse', 'Intercooler Street 3" Grande Metal Horse', 'Intercooler frontal Metal Horse linha Street, núcleo grande de 3 polegadas, melhora o resfriamento em motores turbo.', 2799.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-PLATE-PCV-JETTA', 'plate-eliminador-pcv-metal-horse-vw-jetta-mk6-fusca-211cv', 'Plate Eliminador PCV Metal Horse VW Jetta MK6/Fusca 211cv', 'Plate eliminador de PCV Metal Horse para VW Jetta MK6 e Fusca 211cv, evita reingestão de óleo pela admissão.', 349.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'MH-RADIADOR-10AN', 'radiador-de-oleo-entradasaida-10an-medio--metal-horse', 'Radiador de Óleo Entrada/Saída 10AN Médio Metal Horse', 'Radiador de óleo Metal Horse com entrada e saída 10AN, tamanho médio, melhora o resfriamento do óleo do motor.', 1099.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-SUPORTE-SANDWICH', 'suporte-filtro-de-oleo-p-radiador-sandwich-metal-horse', 'Suporte Filtro de Óleo Sandwich p/ Radiador Metal Horse', 'Suporte sandwich Metal Horse para filtro de óleo, permite instalação de radiador de óleo sem perda de pressão.', 429.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / K&N =====
    (gen_random_uuid(), 'KN-RG1001RD', 'filtro-ar-kn--universal-duplo-fluxo-vermelho-rg1001rd', 'Filtro de Ar K&N Universal Duplo Fluxo Vermelho RG-1001RD', 'Filtro de ar K&N universal RG-1001RD de duplo fluxo, lavável e reutilizável, cor vermelha.', 399.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'KN-INTAKE-14TSI', 'intake-14-tsi-gasolina-filtro-kn-golf-jetta-polo-audi--tbr', 'Intake 1.4 TSI Gasolina Filtro K&N Golf/Jetta/Polo/Audi TBR', 'Kit intake para motores 1.4 TSI gasolina com filtro K&N, compatível com Golf, Jetta, Polo e Audi TBR.', 1199.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'KN-RECHARGER-995050', 'kit-limpeza-filtro-de-ar-kn-recharger-995050--squeeze-red', 'Kit Limpeza Filtro de Ar K&N Recharger 99-5050 Squeeze Red', 'Kit de limpeza e recarga K&N Recharger 99-5050 com frasco squeeze, mantém a eficiência do filtro lavável.', 129.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / FuelTech =====
    (gen_random_uuid(), 'FT-FT700PLUS', 'injeco-programavel-fueltech-ft700plus-sem-chicote', 'Injeção Programável FuelTech FT700 Plus Sem Chicote', 'Central de injeção programável FuelTech FT700 Plus, vendida sem chicote, controle completo de motores aspirados e turbo.', 6499.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'fueltech'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / Pro Line =====
    (gen_random_uuid(), 'PL-DOWNPIPE-CIVIC', 'downpipe-ths-honda-civic-15-turbo-si--touring-3-inox', 'Downpipe Pro Line Honda Civic 1.5 Turbo Si/Touring 3" Inox', 'Downpipe Pro Line em aço inox 3 polegadas para Honda Civic 1.5 Turbo Si/Touring, reduz contrapressão do turbo.', 2299.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'pro-line'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Motor / NGK =====
    (gen_random_uuid(), 'NGK-BOBINA-CIVIC', 'bobina-de-ignicao-new-civic-2007-2008-2009-2010-2011-ngk', 'Bobina de Ignição NGK New Civic 2007-2011', 'Bobina de ignição NGK para New Civic 2007 a 2011, alta confiabilidade na entrega de faísca.', 289.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'NGK-LASERIR-SILZKBR8D8S', 'velas-ngk-laser-iridium-silzkbr8d8s-para-bmw-20-320i-n20', 'Velas NGK Laser Iridium SILZKBR8D8S para BMW 2.0 320i N20', 'Jogo de velas NGK Laser Iridium SILZKBR8D8S, específicas para BMW 2.0 320i motor N20.', 349.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'ACTIVE', NOW(), NOW()),

    -- ===== Motor / Bosch =====
    (gen_random_uuid(), 'BOS-FT450-NANOPRO', 'ft450-nano-pro-sonda-bosch-42-chicote-motor-dianteiro', 'Sonda Lambda Bosch FT450 Nano Pro 4.2 Chicote Motor Dianteiro', 'Sonda lambda Bosch FT450 Nano Pro, conector 4,2 fios, posição dianteira, compatível com centrais FuelTech.', 799.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'bosch'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'BOS-CABOVELA-GOLFAMILY', 'kit-jogo-cabo-e-vela-gol-fox-polo-golf-voyage-saveiro-a3', 'Kit Jogo de Cabo e Vela Bosch Gol/Fox/Polo/Golf/Voyage/Saveiro', 'Kit Bosch com jogo de cabos de vela e velas de ignição, compatível com Gol, Fox, Polo, Golf, Voyage e Saveiro motor EA111.', 249.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'bosch'), 'ACTIVE', NOW(), NOW()),

    -- ===== Motor / AFP =====
    (gen_random_uuid(), 'AFP-PISTAO-825-AP20', 'kit-pistao-forjado-afp-825mm-bielas-mtr-ap-20-turbo-800cv', 'Kit Pistão Forjado AFP 82.5mm com Bielas MTR AP 2.0 Turbo 800cv', 'Kit de pistões forjados AFP 82,5mm com bielas MTR, desenvolvido para motor AP 2.0 turbo com até 800cv.', 4999.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'afp'), 'ACTIVE', NOW(), NOW()),

    -- ===== Freios / Brembo =====
    (gen_random_uuid(), 'BRE-CAPA-PINCA-UNIV', 'capas-para-pinca-de-freio-brembo-encaixe-universal-com-trava', 'Capas para Pinça de Freio Brembo Encaixe Universal com Trava', 'Capas decorativas Brembo para pinça de freio, encaixe universal com sistema de trava.', 349.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-DISCO-A3S3GOLF', 'par-disco-de-freio-diant-brembo-a3-s3-golf-jetta-tiguan', 'Par Disco de Freio Dianteiro Brembo A3/S3/Golf/Jetta/Tiguan', 'Par de discos de freio dianteiros Brembo, ventilados, compatíveis com A3, S3, Golf, Jetta e Tiguan.', 1099.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-PASTILHA-CERAMICA-GLI', 'pastilhas-de-freio-brembo-ceramica-vw-jetta-gli-20-2022', 'Pastilhas de Freio Brembo Cerâmica VW Jetta GLI 2.0 2022', 'Pastilhas de freio Brembo em cerâmica para VW Jetta GLI 2.0 2022, baixa geração de pó e alta resposta.', 599.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Iluminação / OSRAM =====
    (gen_random_uuid(), 'OSR-H7LED-6000K', 'kit-h7-led-osram--6000k', 'Kit LED H7 Osram 6000K', 'Kit de conversão LED Osram H7 com temperatura de cor 6000K, instalação plug and play.', 449.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-COOLBLUE-JETTA0610', 'lampada-farol-baixo-jetta-0610-osram-cool-blue-intense-h7', 'Lâmpada Farol Baixo Jetta 06-10 Osram Cool Blue Intense H7', 'Lâmpada Osram Cool Blue Intense H7 para farol baixo do Jetta 2006 a 2010, luz branco-azulada de efeito xenon.', 179.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-NIGHTBREAKER-JETTA1520', 'lampada-farol-baixo-jetta-1520-osram-night-breaker-laser-h7', 'Lâmpada Farol Baixo Jetta 15-20 Osram Night Breaker Laser H7', 'Lâmpada Osram Night Breaker Laser H7 para farol baixo do Jetta 2015 a 2020, até 150% mais luz.', 199.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'INACTIVE', NOW(), NOW()),

    -- ===== Iluminação / Philips =====
    (gen_random_uuid(), 'PHI-CRISTALVISION-H4PAR', 'kit-lampada-cristal-vision-h4--pingo-original-philips-par', 'Kit Lâmpada Cristal Vision H4 + Pingo Original Philips (Par)', 'Kit Philips com par de lâmpadas Cristal Vision H4 e lâmpadas pingo originais, efeito de luz branca.', 149.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'philips'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'PHI-DIAMONDVISION-H4', 'lampadas-philips-diamond-vision-5000k-h4--certificada-', 'Lâmpadas Philips Diamond Vision 5000K H4 Certificada', 'Par de lâmpadas Philips Diamond Vision H4, temperatura de cor 5000K, certificada para uso em vias públicas.', 169.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'philips'), 'ACTIVE', NOW(), NOW()),

    -- ===== Limpeza / Vonixx =====
    (gen_random_uuid(), 'VON-VMOL', 'vonixx-v-mol-shampoo-automotivo', 'Vonixx V-Mol Shampoo Automotivo', 'Shampoo automotivo Vonixx V-Mol, fórmula neutra de alta lubrificação que evita microrriscos na lavagem.', 44.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-VFLOC-3L', 'v-floc-shampoo-automotivo-neutro-concentrado-3l-vonixx', 'V-Floc Shampoo Automotivo Neutro Concentrado 3L Vonixx', 'Shampoo automotivo Vonixx V-Floc neutro concentrado, embalagem de 3 litros, alto rendimento.', 89.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-VPLASTIC-20ML', 'vitrificador-v-plastic-vonixx-para-plasticos-20ml', 'Vitrificador V-Plastic Vonixx para Plásticos 20ml', 'Vitrificador Vonixx V-Plastic para plásticos externos, proteção e acabamento fosco de longa duração.', 54.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-DELET-15L', 'delet-vonixx-limpador-para-pneus-e-borrachas-15l', 'Delet Vonixx Limpador para Pneus e Borrachas 1.5L', 'Limpador Vonixx Delet para pneus e borrachas, remove pretinhos oxidados e prepara a superfície para novo acabamento.', 64.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'VON-KIT-LAVAGEM', 'kit-lavagem-automotiva-v-floc-blend-sintra-intense-vonixx', 'Kit Lavagem Automotiva V-Floc + Blend + Sintra Intense Vonixx', 'Kit de lavagem automotiva Vonixx com V-Floc, Blend e Sintra Intense, para lavagem e proteção completa da pintura.', 179.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-KIT-SNOWFOAM', 'kit-snow-foam-2l-shampoo-vfloc-vmol-pretinho-sintra-vonixx', 'Kit Snow Foam 2L Shampoo V-Floc + V-Mol + Pretinho + Sintra Vonixx', 'Kit Vonixx Snow Foam 2L com shampoos V-Floc e V-Mol, pretinho de pneu e Sintra, lavagem completa com espuma.', 219.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),

    -- ===== Limpeza / Cadillac =====
    (gen_random_uuid(), 'CAD-NEVASCA-15L-KIT', 'nevasca-15l-shampoo-concentrado-11600-cadillac-luva-toalha', 'Nevasca 1.5L Shampoo Concentrado 1:600 Cadillac + Luva + Toalha', 'Shampoo automotivo Cadillac Nevasca concentrado 1:600, 1,5L, acompanha luva e toalha de microfibra.', 79.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-NEVASCA-15L-DEMOLIDOR', 'nevasca-15l-shampoo-concentrado-cadillac-demolidor-15l', 'Nevasca 1.5L Shampoo Concentrado Cadillac + Demolidor 1.5L', 'Kit Cadillac com shampoo Nevasca concentrado 1,5L e desengraxante Demolidor 1,5L, para lavagem pesada.', 94.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-NEVASCA-500ML', 'nevasca-500ml-cadillac-shampoo-neutro-concentrado-11600', 'Nevasca 500ml Cadillac Shampoo Neutro Concentrado 1:600', 'Shampoo automotivo Cadillac Nevasca neutro concentrado 1:600, embalagem de 500ml.', 29.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-DESENGRAXANTE-MULTI', 'kit-desengraxante-multiuso-dissolve-tira-graxa-oleo-cadillac', 'Kit Desengraxante Multiuso Cadillac Dissolve Tira Graxa e Óleo', 'Desengraxante multiuso Cadillac, dissolve graxa e óleo em motor, peças e piso de garagem.', 49.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-DILUVIO-EXPRESS-500ML', 'selador-de-lavagem-diluvio-express-cadillac-automotivo-500ml', 'Selador de Lavagem Dilúvio Express Cadillac Automotivo 500ml', 'Selador de lavagem Cadillac Dilúvio Express, aplicação rápida durante a lavagem, efeito hidrofóbico.', 39.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Rodas / BBS =====
    (gen_random_uuid(), 'BBS-CIR-GT7-17-5X114', 'jogo-de-rodas-aro-17-5x114-bbs-ci-r-gt7-civic-i30-cerato', 'Jogo de Rodas Aro 17 5x114 BBS CI-R GT7 Civic/i30/Cerato', 'Jogo de rodas BBS CI-R GT7 aro 17, furação 5x114, compatível com Civic, i30 e Cerato.', 4299.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-LM-NV37-17-4X100', 'roda-aro-17-4x100-bbs-lm-nv37-esportivas-racing-4-rodas-jogo', 'Jogo Rodas Aro 17 4x100 BBS LM NV37 Esportivas Racing', 'Jogo de rodas esportivas BBS LM NV37 aro 17, furação 4x100, design clássico de 5 raios duplos.', 3999.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-CIR-GT7-HRVZRV', 'rodas-bbs-ci-r-gt7-aro-17-honda-civic-hrv-zrv-5x114', 'Rodas BBS CI-R GT7 Aro 17 Honda Civic/HR-V/ZR-V 5x114', 'Rodas BBS CI-R GT7 aro 17, furação 5x114, compatíveis com Honda Civic, HR-V e ZR-V.', 4399.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'ACTIVE', NOW(), NOW()),

    -- ===== Rodas / Enkei =====
    (gen_random_uuid(), 'ENK-EV5-17-TALA7', 'roda-aro-17-tala-7-offset-45-4x-100-e-1143--enkei-ev5', 'Roda Aro 17 Tala 7 Offset 45 4x100/4x114.3 Enkei EV5', 'Roda Enkei EV5 aro 17, tala 7, offset 45, dupla furação 4x100 e 4x114,3.', 2599.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'ACTIVE', NOW(), NOW()),

    -- ===== Rodas / OZ Racing =====
    (gen_random_uuid(), 'OZ-UP-17-4X100', 'jogo-roda-aro-17-4x100-oz-racing-up-gol-punto-bar-sunline', 'Jogo Roda Aro 17 4x100 OZ Racing Up! Gol/Punto/Bravo Sunline', 'Jogo de rodas OZ Racing linha Sunline aro 17, furação 4x100, compatível com Up!, Gol, Punto e Bravo.', 3199.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'oz-racing'), 'INACTIVE', NOW(), NOW()),

    -- ===== Pneus / Michelin =====
    (gen_random_uuid(), 'MIC-KIT4-PRIMACY4-2055516', 'kit-4-pneu-aro-16-20555r16-91v-tl-primacy-4-michelin', 'Kit 4 Pneu Aro 16 205/55R16 91V TL Primacy 4 Michelin', 'Kit com 4 pneus Michelin Primacy 4, medida 205/55R16 91V TL, conforto e economia para uso diário.', 2599.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-KIT2-PS5-2254518', 'kit-de-2-pneus-michelin-pilot-pilot-sport-5-p-22545r18-95', 'Kit 2 Pneus Michelin Pilot Sport 5 225/45R18 95Y', 'Kit com 2 pneus Michelin Pilot Sport 5, medida 225/45R18 95Y, alta performance em piso seco e molhado.', 2199.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-PRIMACY4-2156516', 'pneu-michelin-primacy-4-p-21565r16-102-h', 'Pneu Michelin Primacy 4 215/65R16 102H', 'Pneu Michelin Primacy 4, medida 215/65R16 102H, conforto e boa frenagem em piso molhado.', 749.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Pneus / Goodyear =====
    (gen_random_uuid(), 'GY-EAGLESPORT2-1856515', 'pneu-18565r15-goodyear-eagle-sport-2-88h-indice-de-velocidade-h', 'Pneu 185/65R15 Goodyear Eagle Sport 2 88H', 'Pneu Goodyear Eagle Sport 2, medida 185/65R15, índice de carga 88 e velocidade H.', 449.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'GY-EAGLETOURING-2054518', 'pneu-20545r18-goodyear-eagle-touring-86v-aro-18', 'Pneu 205/45R18 Goodyear Eagle Touring 86V Aro 18', 'Pneu Goodyear Eagle Touring, medida 205/45R18, índice de carga 86 e velocidade V.', 649.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'ACTIVE', NOW(), NOW()),

    -- ===== Suspensão / Eibach =====
    (gen_random_uuid(), 'EIB-KIT-BARRAS-ESTAB', 'kit-de-barras-estabilizadoras-eibach', 'Kit de Barras Estabilizadoras Eibach', 'Kit de barras estabilizadoras Eibach dianteira e traseira, reduz a rolagem da carroceria em curvas.', 999.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-SPORTLINE-JETTA-MK6', 'kit-sportline-mola-eibach-vw-jetta-mk6-20-tsi-2011-2017', 'Kit Sportline Mola Eibach VW Jetta MK6 2.0 TSI 2011-2017', 'Kit de molas Eibach Sportline para VW Jetta MK6 2.0 TSI 2011 a 2017, rebaixamento esportivo.', 1099.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-PROKIT-POLOVIRTUS', 'molas-esportivas-eibach-pro-kit-polo-virtus-tsi-gts-mpi-msi', 'Molas Esportivas Eibach Pro-Kit Polo/Virtus TSI GTS MPI MSI', 'Molas esportivas Eibach Pro-Kit para Polo e Virtus TSI, GTS, MPI e MSI, reduz altura mantendo conforto.', 949.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Suspensão / D2 Racing =====
    (gen_random_uuid(), 'D2R-COILOVER-CIVIC-TRACKDAY', 'kit-suspensao-new-civic-trackday-hotlap-coilover', 'Kit Suspensão D2 Racing New Civic Trackday Hotlap Coilover', 'Kit de suspensão coilover D2 Racing linha Trackday Hotlap para New Civic, regulagem de altura.', 4599.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-ROSCA-SLIM-LANCER', 'kit-suspensao-rosca-slim-lancer--modelo-premium', 'Kit Suspensão Rosca Slim D2 Racing Lancer Modelo Premium', 'Kit de suspensão rosca slim D2 Racing modelo Premium para Lancer, regulagem de altura dianteira e traseira.', 2299.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-STREET-IMPREZA-GCGF', 'suspensao-coilover-d2-racing-street-subaru-impreza-gcgf-199', 'Suspensão Coilover D2 Racing Street Subaru Impreza GC/GF 1999+', 'Coilover D2 Racing Street para Subaru Impreza GC/GF a partir de 1999, focado em conforto com leve rebaixamento.', 4899.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-COILOVER-CIVIC0714', 'suspensao-coilover--honda-civic-0714', 'Suspensão Coilover D2 Racing Honda Civic 07-14', 'Coilover D2 Racing para Honda Civic 2007 a 2014, regulagem de altura dianteira e traseira independente.', 3799.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW());
