INSERT INTO products (id, sku, slug, name, description, price, category_id, brand_id, status, created_at, updated_at) VALUES

    -- ===== Acessórios / Recaro =====
    (gen_random_uuid(), 'REC-SPORTSTER-CS', 'banco-esportivo-recaro-sportster-cs', 'Banco Esportivo Recaro Sportster CS', 'Banco esportivo Recaro Sportster CS com bom suporte lateral, indicado para uso diário e esportivo.', 6999.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'recaro'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'REC-POLEPOSITION', 'banco-esportivo-recaro-pole-position', 'Banco Esportivo Recaro Pole Position', 'Banco esportivo Recaro Pole Position, homologado para competição com estrutura em fibra de carbono.', 8999.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'recaro'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'REC-ORTHOPED', 'banco-recaro-orthoped', 'Banco Recaro Orthopéd', 'Banco Recaro Orthopéd com design ergonômico, focado em conforto em viagens longas.', 5499.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'recaro'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'REC-CROSS-SPORTSTER', 'banco-esportivo-recaro-cross-sportster', 'Banco Esportivo Recaro Cross Sportster', 'Banco esportivo Recaro Cross Sportster, indicado para SUVs e uso misto rua/off-road leve.', 7499.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'recaro'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'REC-STYLETOPLINE', 'banco-recaro-style-topline', 'Banco Recaro Style Topline', 'Banco Recaro Style Topline com acabamento premium em couro, foco em conforto e elegância.', 4999.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'recaro'), 'INACTIVE', NOW(), NOW()),

    -- ===== Acessórios / Thule =====
    (gen_random_uuid(), 'THU-WINGBAR-EVO', 'rack-de-teto-thule-wingbar-evo', 'Rack de Teto Thule WingBar Evo', 'Barra de teto Thule WingBar Evo em alumínio, baixo ruído aerodinâmico e alta capacidade de carga.', 1299.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'thule'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'THU-PRORIDE-598', 'suporte-bike-thule-proride-598', 'Suporte para Bike Thule ProRide 598', 'Suporte de teto Thule ProRide 598 para uma bicicleta, fixação sem contato com o quadro.', 899.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'thule'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'THU-MOTION-XT-L', 'bau-de-teto-thule-motion-xt-l', 'Baú de Teto Thule Motion XT L', 'Baú de teto Thule Motion XT L com abertura dupla e 460 litros de capacidade.', 3499.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'thule'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'THU-EASYFOLD-XT2', 'suporte-bike-thule-easyfold-xt-2', 'Suporte para Bike Thule EasyFold XT 2', 'Suporte de engate Thule EasyFold XT 2, dobrável e para até duas bicicletas.', 2799.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'thule'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'THU-KIDSBACK', 'cadeirinha-thule-kidsback', 'Cadeirinha Thule Kids-Back', 'Cadeirinha infantil Thule Kids-Back para transporte seguro em bicicletas.', 599.90, (SELECT id FROM categories WHERE slug = 'acessorios'), (SELECT id FROM brands WHERE slug = 'thule'), 'ACTIVE', NOW(), NOW()),

    -- ===== Escapamento / Luzian =====
    (gen_random_uuid(), 'LUZ-RACING-TURBO', 'escapamento-luzian-racing-turbo', 'Escapamento Luzian Racing Turbo', 'Escapamento esportivo Luzian Racing Turbo em aço inox, som grave e acabamento polido.', 1899.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'luzian'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'LUZ-INOX-304', 'escapamento-luzian-inox-304', 'Escapamento Luzian Inox 304', 'Escapamento Luzian confeccionado em aço inox 304, alta resistência à corrosão.', 1599.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'luzian'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'LUZ-GRAFITE-ESPORTIVO', 'escapamento-luzian-grafite-esportivo', 'Escapamento Luzian Grafite Esportivo', 'Escapamento esportivo Luzian com ponteira grafite, visual agressivo e som encorpado.', 1799.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'luzian'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'LUZ-SPORTLINE', 'escapamento-luzian-sport-line', 'Escapamento Luzian Sport Line', 'Escapamento Luzian Sport Line com válvula reguladora de som, uso na rua e track day.', 2199.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'luzian'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'LUZ-TURBOLINE', 'escapamento-luzian-turbo-line', 'Escapamento Luzian Turbo Line', 'Escapamento Luzian Turbo Line com maior diâmetro de saída para veículos turbo.', 2399.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'luzian'), 'ACTIVE', NOW(), NOW()),

    -- ===== Escapamento / Akrapovič =====
    (gen_random_uuid(), 'AKR-EVO-TI', 'escapamento-akrapovic-evolution-titanium', 'Escapamento Akrapovič Evolution Titanium', 'Escapamento Akrapovič Evolution linha completa em titânio. Redução de peso, aumento de potência e som esportivo inconfundível.', 7899.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'akrapovic'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'AKR-SLIPON-CARBON', 'escapamento-akrapovic-slip-on-carbon', 'Escapamento Akrapovič Slip-On Carbon', 'Escapamento Akrapovič Slip-On com ponteira em fibra de carbono, ganho de potência e som esportivo.', 4999.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'akrapovic'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'AKR-EVOLINE-STEEL', 'escapamento-akrapovic-evolution-line-steel', 'Escapamento Akrapovič Evolution Line Steel', 'Escapamento Akrapovič Evolution Line em aço inoxidável, alternativa mais acessível à linha titânio.', 5999.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'akrapovic'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'AKR-RACINGLINE-TI', 'escapamento-akrapovic-racing-line-titanium', 'Escapamento Akrapovič Racing Line Titanium', 'Escapamento Akrapovič Racing Line em titânio, voltado exclusivamente para uso em pista.', 8999.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'akrapovic'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'AKR-GPLINE-TI', 'escapamento-akrapovic-gp-line-titanium', 'Escapamento Akrapovič GP Line Titanium', 'Escapamento Akrapovič GP Line em titânio, tecnologia de competição para máxima performance.', 10999.90, (SELECT id FROM categories WHERE slug = 'escapamento'), (SELECT id FROM brands WHERE slug = 'akrapovic'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Freios / Brembo =====
    (gen_random_uuid(), 'BRE-GT-330', 'kit-freios-brembo-sport-gt', 'Kit Freios Brembo Sport GT', 'Kit de freios esportivos Brembo GT com discos perfurados e pastilhas de alta performance. Para uso intenso em pista e rua.', 3299.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-HP2000-F', 'pastilhas-brembo-hp2000-dianteira', 'Pastilhas Brembo HP2000 Dianteira', 'Pastilhas de freio Brembo HP2000 para uso esportivo. Alta resistência ao fade térmico, ideais para uso misto rua/pista.', 289.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-XTRA-330', 'disco-freio-brembo-xtra-330mm', 'Disco de Freio Brembo Xtra 330mm', 'Disco de freio Brembo Xtra perfurado 330mm, melhor dissipação de calor e visual esportivo.', 899.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-MAXPRO', 'kit-freios-brembo-max-pro', 'Kit Freios Brembo Max Pro', 'Kit de freios Brembo Max Pro com discos ventilados e pastilhas de cerâmica para uso misto.', 3899.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'BRE-SPORT-TRAS', 'disco-freio-brembo-sport-traseiro', 'Disco de Freio Brembo Sport Traseiro', 'Disco de freio Brembo Sport traseiro, ventilado, com excelente resposta de frenagem.', 799.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'brembo'), 'ACTIVE', NOW(), NOW()),

    -- ===== Freios / Ferodo =====
    (gen_random_uuid(), 'FER-DS2500', 'pastilha-ferodo-ds2500', 'Pastilha de Freio Ferodo DS2500', 'Pastilha de freio Ferodo DS2500, alta performance para uso misto rua e track day.', 449.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'ferodo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'FER-RACING-4001', 'pastilha-ferodo-racing-4001', 'Pastilha de Freio Ferodo Racing 4001', 'Pastilha de freio Ferodo Racing 4001, desenvolvida para competição com resposta consistente a altas temperaturas.', 599.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'ferodo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'FER-PREMIER-ADA', 'pastilha-ferodo-premier-ada', 'Pastilha de Freio Ferodo Premier ADA', 'Pastilha de freio Ferodo Premier ADA, baixo ruído e baixa geração de pó para uso diário.', 259.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'ferodo'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'FER-DS-PERFORMANCE', 'pastilha-ferodo-ds-performance', 'Pastilha de Freio Ferodo DS Performance', 'Pastilha de freio Ferodo DS Performance, equilíbrio entre conforto e resposta esportiva.', 399.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'ferodo'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'FER-RACING-DISC', 'disco-freio-ferodo-racing', 'Disco de Freio Ferodo Racing', 'Disco de freio Ferodo Racing perfurado e ventilado, alta dissipação térmica.', 749.90, (SELECT id FROM categories WHERE slug = 'freios'), (SELECT id FROM brands WHERE slug = 'ferodo'), 'INACTIVE', NOW(), NOW()),

    -- ===== Iluminação / OSRAM =====
    (gen_random_uuid(), 'OSR-NIGHT-H7', 'lampada-osram-night-breaker-laser-h7', 'Lâmpada Osram Night Breaker Laser H7', 'Lâmpada halógena Osram Night Breaker Laser H7, até 150% mais luz que uma lâmpada padrão.', 189.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-COOL-H4', 'lampada-osram-cool-blue-intense-h4', 'Lâmpada Osram Cool Blue Intense H4', 'Lâmpada Osram Cool Blue Intense H4 com luz branco-azulada de efeito xenon.', 159.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-LEDRIVING-H11', 'farol-led-osram-ledriving-h11', 'Farol LED Osram LEDriving H11', 'Kit de conversão LED Osram LEDriving H11, plug and play com alto fluxo luminoso.', 599.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-LEDRIVING-H7', 'kit-led-osram-ledriving-h7', 'Kit LED Osram LEDriving H7', 'Kit de conversão LED Osram LEDriving H7, instalação plug and play e alta durabilidade.', 579.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'OSR-ORIGINAL-H1', 'lampada-osram-original-line-h1', 'Lâmpada Osram Original Line H1', 'Lâmpada halógena Osram Original Line H1, padrão de fábrica com qualidade OEM.', 89.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'osram'), 'ACTIVE', NOW(), NOW()),

    -- ===== Iluminação / Hella =====
    (gen_random_uuid(), 'HEL-LUMINATOR-LED', 'farol-milha-hella-luminator-led', 'Farol de Milha Hella Luminator LED', 'Farol de milha Hella Luminator LED de longo alcance, ideal para estrada e trilha.', 1899.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'hella'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'HEL-RALLYE4000', 'farol-auxiliar-hella-rallye-4000', 'Farol Auxiliar Hella Rallye 4000', 'Farol auxiliar Hella Rallye 4000, clássico em rally com feixe de longo alcance.', 2199.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'hella'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'HEL-COMET500', 'farol-milha-hella-comet-500', 'Farol de Milha Hella Comet 500', 'Farol de milha Hella Comet 500 compacto, boa dispersão de luz para uso urbano e estrada.', 999.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'hella'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'HEL-FF75', 'farol-auxiliar-hella-ff75', 'Farol Auxiliar Hella FF75', 'Farol auxiliar Hella FF75 compacto, feixe de longo alcance para uso rodoviário.', 1099.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'hella'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'HEL-MARINELIGHT', 'lanterna-led-hella-marinelight', 'Lanterna LED Hella Marinelight', 'Lanterna LED Hella Marinelight de alta visibilidade, resistente à água.', 349.90, (SELECT id FROM categories WHERE slug = 'iluminacao'), (SELECT id FROM brands WHERE slug = 'hella'), 'ACTIVE', NOW(), NOW()),

    -- ===== Limpeza / Vonixx =====
    (gen_random_uuid(), 'VON-SEALFLON', 'selante-vonixx-sealflon', 'Selante Vonixx Sealflon', 'Selante de pintura Vonixx Sealflon à base de polímeros, proteção e brilho de longa duração.', 89.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-BANANABOOST', 'shampoo-automotivo-vonixx-banana-boost', 'Shampoo Automotivo Vonixx Banana Boost', 'Shampoo automotivo Vonixx Banana Boost, fórmula neutra com fragrância de banana.', 39.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-NEVE-PRETINHO', 'pretinho-pneu-vonixx-neve', 'Pretinho de Pneu Vonixx Neve', 'Renovador de pneus Vonixx Neve em gel, alto teor de silicone e efeito duradouro.', 44.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-WASHFAST', 'vonixx-wash-fast', 'Vonixx Wash Fast', 'Shampoo de lavagem rápida Vonixx Wash Fast, sem necessidade de enxágue abundante.', 49.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'VON-VWAX', 'cera-vonixx-v-wax', 'Cera Vonixx V-Wax', 'Cera automotiva Vonixx V-Wax em pasta, alto brilho e proteção contra intempéries.', 69.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'vonixx'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Limpeza / Cadillac =====
    (gen_random_uuid(), 'CAD-SHAMPOO-CONC', 'shampoo-concentrado-cadillac', 'Shampoo Concentrado Cadillac', 'Shampoo automotivo concentrado Cadillac, alta diluição e boa espuma para lavagem.', 34.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-CLEANER-WAX', 'cera-cleaner-wax-cadillac', 'Cera Cleaner Wax Cadillac', 'Cera limpadora Cadillac Cleaner Wax, remove oxidação leve e devolve o brilho da pintura.', 54.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-APC-MULTIUSO', 'apc-multiuso-cadillac', 'APC Multiuso Cadillac', 'Limpador multiuso concentrado Cadillac para painéis, carpetes e estofados.', 29.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-REVITALIZADOR', 'revitalizador-plasticos-cadillac', 'Revitalizador de Plásticos Cadillac', 'Revitalizador de plásticos internos e externos Cadillac, proteção contra ressecamento.', 39.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'CAD-SILICONE-SPRAY', 'silicone-spray-cadillac', 'Silicone Spray Cadillac', 'Silicone spray Cadillac para acabamento em plásticos, borrachas e painéis.', 24.90, (SELECT id FROM categories WHERE slug = 'limpeza'), (SELECT id FROM brands WHERE slug = 'cadillac'), 'ACTIVE', NOW(), NOW()),

    -- ===== Motor / Mahle =====
    (gen_random_uuid(), 'MAH-FILTRO-OLEO-OC90', 'filtro-oleo-mahle-oc90', 'Filtro de Óleo Mahle OC90', 'Filtro de óleo Mahle OC90, alta capacidade de retenção de partículas para proteção do motor.', 39.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'mahle'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MAH-FILTRO-AR-LX1234', 'filtro-ar-mahle-lx1234', 'Filtro de Ar Mahle LX1234', 'Filtro de ar Mahle LX1234 de fábrica, garante fluxo de ar limpo para o motor.', 69.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'mahle'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MAH-KIT-PISTAO-TURBO', 'kit-pistao-mahle-turbo', 'Kit Pistão Mahle Turbo', 'Kit de pistões Mahle para motores turbo, alta resistência térmica e mecânica.', 2199.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'mahle'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'MAH-JUNTA-CABECOTE', 'junta-cabecote-mahle', 'Junta do Cabeçote Mahle', 'Junta de cabeçote Mahle Original, vedação de fábrica para motores a gasolina e flex.', 249.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'mahle'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MAH-FILTRO-COMB-KL145', 'filtro-combustivel-mahle-kl145', 'Filtro de Combustível Mahle KL145', 'Filtro de combustível Mahle KL145, filtragem eficiente para injeção eletrônica.', 79.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'mahle'), 'INACTIVE', NOW(), NOW()),

    -- ===== Motor / NGK =====
    (gen_random_uuid(), 'NGK-IRIDIUM-IX', 'vela-ngk-iridium-ix', 'Vela de Ignição NGK Iridium IX', 'Vela de ignição NGK Iridium IX, eletrodo fino para melhor combustão e economia.', 79.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'NGK-PLATINUM', 'vela-ngk-platinum', 'Vela de Ignição NGK Platinum', 'Vela de ignição NGK Platinum, maior durabilidade e estabilidade de combustão.', 59.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'NGK-CABO-RACING', 'cabo-vela-ngk-racing', 'Cabo de Vela NGK Racing', 'Jogo de cabos de vela NGK Racing, baixa resistência elétrica para máxima performance.', 249.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'NGK-STANDARD-BKR6E', 'vela-ngk-standard-bkr6e', 'Vela NGK Standard BKR6E', 'Vela de ignição NGK Standard BKR6E, padrão de fábrica para diversos modelos.', 29.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'NGK-BOBINA-U5157', 'bobina-ignicao-ngk-u5157', 'Bobina de Ignição NGK U5157', 'Bobina de ignição NGK U5157, alta performance e confiabilidade na entrega de faísca.', 349.90, (SELECT id FROM categories WHERE slug = 'motor'), (SELECT id FROM brands WHERE slug = 'ngk'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / K&N =====
    (gen_random_uuid(), 'KN-33-2385', 'filtro-de-ar-kn-alto-fluxo-33-2385', 'Filtro de Ar K&N Alto Fluxo 33-2385', 'Filtro de ar de alto fluxo K&N reutilizável. Aumenta o fluxo de ar para o motor, melhorando a performance e economia de combustível.', 349.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'KN-63-SERIES', 'kit-admissao-kn-63-series', 'Kit Admissão K&N 63 Series', 'Kit de admissão de ar K&N 63 Series com filtro lavável de alto fluxo, ganho de resposta do motor.', 1099.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'KN-HIGHFLOW-PANEL', 'filtro-de-ar-kn-high-flow-panel', 'Filtro de Ar K&N High-Flow Panel', 'Filtro de ar em painel K&N de alto fluxo, substitui o filtro original mantendo a caixa de ar.', 329.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'KN-COLDAIR-INTAKE', 'kit-admissao-kn-cold-air-intake', 'Kit Admissão K&N Cold Air Intake', 'Kit de admissão de ar frio K&N, capta ar externo mais frio e denso para ganho de potência.', 1499.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'KN-OIL-GOLD', 'filtro-oleo-kn-performance-gold', 'Filtro de Óleo K&N Performance Gold', 'Filtro de óleo K&N Performance Gold, elemento filtrante de alta capacidade de retenção.', 89.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'k-n'), 'ACTIVE', NOW(), NOW()),

    -- ===== Performance / Metal Horse =====
    (gen_random_uuid(), 'MH-TURBO-GT30', 'turbina-metal-horse-gt30', 'Turbina Metal Horse GT30', 'Turbina Metal Horse GT30, alta capacidade de fluxo para motores de médio a alto desempenho.', 3999.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-COLETOR-4-1', 'coletor-escape-metal-horse-4-1', 'Coletor de Escape Metal Horse 4-1', 'Coletor de escape esportivo Metal Horse 4-1 em aço inox, melhora a vazão dos gases.', 1299.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-INTERCOOLER-FMIC', 'intercooler-metal-horse-fmic', 'Intercooler Metal Horse FMIC', 'Intercooler frontal Metal Horse FMIC, maior eficiência de resfriamento para motores turbo.', 2499.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-WASTEGATE-EXT', 'wastegate-externa-metal-horse', 'Wastegate Externa Metal Horse', 'Wastegate externa Metal Horse para controle de pressão de turbo em preparações racing.', 899.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MH-DOWNPIPE-RACING', 'downpipe-racing-metal-horse', 'Downpipe Racing Metal Horse', 'Downpipe Metal Horse em aço inox, reduz contrapressão e aumenta resposta do turbo.', 1799.90, (SELECT id FROM categories WHERE slug = 'performance'), (SELECT id FROM brands WHERE slug = 'metal-horse'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Pneus / Michelin =====
    (gen_random_uuid(), 'MIC-PS4-2254517', 'pneu-michelin-pilot-sport-4-225-45r17', 'Pneu Michelin Pilot Sport 4 225/45R17', 'Pneu de alta performance Michelin Pilot Sport 4. Excelente aderência em piso seco e molhado, ideal para carros esportivos.', 899.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-PS4S-2354018', 'pneu-michelin-pilot-sport-4s-235-40r18', 'Pneu Michelin Pilot Sport 4S 235/40R18', 'Pneu Michelin Pilot Sport 4S para carros esportivos de alta performance, excelente frenagem molhada.', 1299.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-CROSSC-2156516', 'pneu-michelin-crossclimate-2-215-65r16', 'Pneu Michelin CrossClimate 2 215/65R16', 'Pneu Michelin CrossClimate 2, uso em todas as estações com boa performance em piso molhado.', 799.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-CUP2-2354018', 'pneu-michelin-pilot-sport-cup-2-235-40r18', 'Pneu Michelin Pilot Sport Cup 2 235/40R18', 'Pneu Michelin Pilot Sport Cup 2, semi-slick voltado para uso em pista e track days.', 1499.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'MIC-PRIMACY4-2055516', 'pneu-michelin-primacy-4-205-55r16', 'Pneu Michelin Primacy 4 205/55R16', 'Pneu Michelin Primacy 4, conforto e economia para uso diário com boa frenagem molhada.', 649.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'michelin'), 'ACTIVE', NOW(), NOW()),

    -- ===== Pneus / Goodyear =====
    (gen_random_uuid(), 'GY-EAGLEF1-2254017', 'pneu-goodyear-eagle-f1-asymmetric-5-225-40r17', 'Pneu Goodyear Eagle F1 Asymmetric 5 225/40R17', 'Pneu Goodyear Eagle F1 Asymmetric 5, alta performance com excelente resposta em curvas.', 949.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'GY-EFFICIENTGRIP-2054516', 'pneu-goodyear-efficientgrip-performance-205-45r16', 'Pneu Goodyear EfficientGrip Performance 205/45R16', 'Pneu Goodyear EfficientGrip Performance, foco em economia de combustível e conforto.', 649.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'GY-WRANGLER-AT-2657016', 'pneu-goodyear-wrangler-at-265-70r16', 'Pneu Goodyear Wrangler AT 265/70R16', 'Pneu Goodyear Wrangler All-Terrain, para uso misto asfalto e off-road.', 899.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'GY-ASSURANCE-2054516', 'pneu-goodyear-assurance-triplemax-205-45r16', 'Pneu Goodyear Assurance TripleMax 205/45R16', 'Pneu Goodyear Assurance TripleMax, frenagem curta em piso molhado e maior durabilidade.', 599.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'GY-EAGLESPORT-2254017', 'pneu-goodyear-eagle-sport-225-40r17', 'Pneu Goodyear Eagle Sport 225/40R17', 'Pneu Goodyear Eagle Sport, desempenho esportivo com bom custo-benefício.', 799.90, (SELECT id FROM categories WHERE slug = 'pneus'), (SELECT id FROM brands WHERE slug = 'goodyear'), 'INACTIVE', NOW(), NOW()),

    -- ===== Rodas / BBS =====
    (gen_random_uuid(), 'BBS-RS-18', 'rodas-esportivas-aro-18-bbs-rs', 'Rodas Esportivas Aro 18 BBS RS', 'Rodas esportivas BBS RS aro 18 com acabamento em prata. Fabricadas em liga de alumínio de alta resistência, ideais para uso esportivo e pista.', 4899.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-RS-18-BLK', 'rodas-esportivas-aro-18-bbs-rs-black', 'Rodas Esportivas Aro 18 BBS RS Black', 'Rodas esportivas BBS RS aro 18 com acabamento em preto fosco. Fabricadas em liga de alumínio de alta resistência.', 5099.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-CHR-19', 'rodas-esportivas-aro-19-bbs-ch-r', 'Rodas Esportivas Aro 19 BBS CH-R', 'Rodas forjadas BBS CH-R aro 19, construção leve em duas peças para uso esportivo em rua e pista.', 5599.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-LM-19', 'rodas-esportivas-aro-19-bbs-lm', 'Rodas Esportivas Aro 19 BBS LM', 'Rodas BBS LM aro 19, design clássico de 5 raios duplos em liga leve de alumínio fundido.', 5699.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'BBS-SR-17', 'rodas-esportivas-aro-17-bbs-sr', 'Rodas Esportivas Aro 17 BBS SR', 'Rodas BBS SR aro 17, leves e resistentes, ideais para uso diário com toque esportivo.', 4599.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'bbs'), 'ACTIVE', NOW(), NOW()),

    -- ===== Rodas / Enkei =====
    (gen_random_uuid(), 'ENK-RPF1-17', 'rodas-esportivas-aro-17-enkei-rpf1', 'Rodas Esportivas Aro 17 Enkei RPF1', 'Rodas Enkei RPF1 aro 17, uma das mais leves do mercado, muito usadas em competições de time attack.', 2899.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'ENK-RPF1-18', 'rodas-esportivas-aro-18-enkei-rpf1', 'Rodas Esportivas Aro 18 Enkei RPF1', 'Rodas Enkei RPF1 aro 18, uma das mais leves do mercado, muito usadas em competições de time attack.', 3099.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'ENK-NT03-17', 'rodas-esportivas-aro-17-enkei-nt03', 'Rodas Esportivas Aro 17 Enkei NT03+M', 'Rodas Enkei NT03+M aro 17, fundição MAT em alumínio, equilíbrio entre leveza e resistência.', 2999.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'ENK-TSV6-18', 'rodas-esportivas-aro-18-enkei-tsv6', 'Rodas Esportivas Aro 18 Enkei TSV6', 'Rodas Enkei TSV6 aro 18, design de 6 raios duplos com acabamento premium.', 3399.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'ENK-PF01-17', 'rodas-esportivas-aro-17-enkei-pf01', 'Rodas Esportivas Aro 17 Enkei PF01', 'Rodas Enkei PF01 aro 17, ícone JDM leve para uso esportivo e rebaixados.', 2799.90, (SELECT id FROM categories WHERE slug = 'rodas'), (SELECT id FROM brands WHERE slug = 'enkei'), 'ACTIVE', NOW(), NOW()),

    -- ===== Suspensão / Eibach =====
    (gen_random_uuid(), 'EIB-PROKIT-01', 'kit-molas-eibach-pro-kit', 'Kit Molas Eibach Pro-Kit', 'Kit de molas esportivas Eibach Pro-Kit, reduz altura mantendo conforto para uso diário.', 1299.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-SPORTLINE-01', 'kit-molas-eibach-sportline', 'Kit Molas Eibach Sportline', 'Kit de molas Eibach Sportline com rebaixamento mais agressivo para visual e dirigibilidade esportiva.', 1399.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-PROSTREET-S', 'suspensao-eibach-pro-street-s', 'Suspensão Eibach Pro-Street-S', 'Coilover Eibach Pro-Street-S com regulagem de altura dianteira e traseira independente.', 4999.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-ANTIROLL-FRONT', 'barra-estabilizadora-eibach-dianteira', 'Barra Estabilizadora Eibach Dianteira', 'Barra estabilizadora Eibach dianteira, reduz a rolagem da carroceria em curvas.', 899.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'EIB-MULTIPRO-R2', 'suspensao-eibach-multi-pro-r2', 'Suspensão Eibach Multi-Pro R2', 'Coilover Eibach Multi-Pro R2 com regulagem de rebound em 16 posições para uso em pista.', 5499.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'eibach'), 'OUT_OF_STOCK', NOW(), NOW()),

    -- ===== Suspensão / D2 Racing =====
    (gen_random_uuid(), 'D2R-RS-COILOVER', 'suspensao-coilover-d2-racing-rs', 'Suspensão Coilover D2 Racing RS', 'Coilover D2 Racing RS com regulagem de altura, boa relação custo-benefício para uso esportivo.', 3299.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'INACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-STREET-COILOVER', 'suspensao-coilover-d2-racing-street', 'Suspensão Coilover D2 Racing Street', 'Coilover D2 Racing Street, focado em conforto com leve rebaixamento para uso diário.', 2999.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-ZEAL-COILOVER', 'suspensao-coilover-d2-racing-zeal', 'Suspensão Coilover D2 Racing Zeal', 'Coilover D2 Racing Zeal com regulagem de compressão e rebound de 32 estágios.', 4299.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-CIRCUIT-COILOVER', 'suspensao-coilover-d2-racing-circuit', 'Suspensão Coilover D2 Racing Circuit', 'Coilover D2 Racing Circuit, desenvolvido para uso intensivo em pista.', 5299.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'OUT_OF_STOCK', NOW(), NOW()),
    (gen_random_uuid(), 'D2R-DRIFT-COILOVER', 'suspensao-coilover-d2-racing-drift', 'Suspensão Coilover D2 Racing Drift', 'Coilover D2 Racing Drift com ângulo de câmber ajustável, voltado para drift.', 4799.90, (SELECT id FROM categories WHERE slug = 'suspensao'), (SELECT id FROM brands WHERE slug = 'd2-racing'), 'ACTIVE', NOW(), NOW());
